### ISSUE TITLE
[Bug] Installer doesn't generate a new hardware configuration file - Can't boot after install

### ISSUE THREAD

**Issue by dwilliam62** [Voxi0/NixDots#2]
As we chatting on discord.  The hardware config file that gets installed is from your repo.  I don't see where is generates a new one during the install. 

I did try to generate a new one after from live ISO, but apparently I have a skill issue and couldn't make it work.

**Comment by Voxi0** [comment]
Fixed. Now the installer generates a new 'hardware-configuration.nix' file during install.
